import {meta, parseForESLint} from "jsonc-eslint-parser";
import packageJsonPlugin from "eslint-plugin-package-json";
import type {Linter} from "eslint";

import {PACKAGE_JSON_FILES} from "../globs";

const packageJsonRules: Linter.RulesRecord = {
  "package-json/no-empty-fields": "error",
  "package-json/no-redundant-files": "error",
  "package-json/no-redundant-publishConfig": "error",
  "package-json/repository-shorthand": "error",
  "package-json/require-attribution": "error",
  "package-json/require-description": "error",
  "package-json/require-exports": "error",
  "package-json/require-files": "error",
  "package-json/require-license": "error",
  "package-json/require-name": "error",
  "package-json/require-repository": "error",
  "package-json/require-sideEffects": "error",
  "package-json/require-type": "error",
  "package-json/require-version": "error",
  "package-json/sort-collections": "error",
  "package-json/specify-peers-locally": "error",
  "package-json/unique-dependencies": "error",
  "package-json/valid-author": "error",
  "package-json/valid-bin": "error",
  "package-json/valid-browser": "error",
  "package-json/valid-bugs": "error",
  "package-json/valid-bundleDependencies": "error",
  "package-json/valid-config": "error",
  "package-json/valid-contributors": "error",
  "package-json/valid-cpu": "error",
  "package-json/valid-dependencies": "error",
  "package-json/valid-description": "error",
  "package-json/valid-devDependencies": "error",
  "package-json/valid-devEngines": "error",
  "package-json/valid-directories": "error",
  "package-json/valid-engines": "error",
  "package-json/valid-exports": "error",
  "package-json/valid-files": "error",
  "package-json/valid-funding": "error",
  "package-json/valid-gypfile": "error",
  "package-json/valid-homepage": "error",
  "package-json/valid-keywords": "error",
  "package-json/valid-libc": "error",
  "package-json/valid-license": "error",
  "package-json/valid-main": "error",
  "package-json/valid-man": "error",
  "package-json/valid-module": "error",
  "package-json/valid-name": "error",
  "package-json/valid-optionalDependencies": "error",
  "package-json/valid-os": "error",
  "package-json/valid-packageManager": "error",
  "package-json/valid-peerDependencies": "error",
  "package-json/valid-peerDependenciesMeta": "error",
  "package-json/valid-peerDependenciesMeta-relationship": "error",
  "package-json/valid-private": "error",
  "package-json/valid-publishConfig": "error",
  "package-json/valid-repository": "error",
  "package-json/valid-repository-directory": "error",
  "package-json/valid-scripts": "error",
  "package-json/valid-sideEffects": "error",
  "package-json/valid-type": "error",
  "package-json/valid-version": "error",
  "package-json/valid-workspaces": "error",
};

export const packageJson: Linter.Config[] = [
  {
    files: PACKAGE_JSON_FILES,
    name: "yarapa/package-json",
    languageOptions: {
      parser: {
        meta,
        parseForESLint,
      },
    },
    plugins: {
      "package-json": packageJsonPlugin,
    },
    rules: packageJsonRules,
  },
];
