import eslintReact from "@eslint-react/eslint-plugin";
import type {Linter} from "eslint";

import {REACT_FILES} from "../globs";

const reactRules: Linter.RulesRecord = {
  "@eslint-react/dom-no-dangerously-set-innerhtml": "error",
  "@eslint-react/dom-no-dangerously-set-innerhtml-with-children": "error",
  "@eslint-react/dom-no-find-dom-node": "error",
  "@eslint-react/dom-no-flush-sync": "error",
  "@eslint-react/dom-no-hydrate": "error",
  "@eslint-react/dom-no-render": "error",
  "@eslint-react/dom-no-render-return-value": "error",
  "@eslint-react/dom-no-script-url": "error",
  "@eslint-react/dom-no-unknown-property": "error",
  "@eslint-react/dom-no-unsafe-iframe-sandbox": "error",
  "@eslint-react/dom-no-unsafe-target-blank": "error",
  "@eslint-react/dom-no-use-form-state": "error",
  "@eslint-react/dom-no-void-elements-with-children": "error",
  "@eslint-react/error-boundaries": "error",
  "@eslint-react/exhaustive-deps": "error",
  "@eslint-react/jsx-no-children-prop": "error",
  "@eslint-react/jsx-no-children-prop-with-children": "error",
  "@eslint-react/jsx-no-comment-textnodes": "error",
  "@eslint-react/jsx-no-key-after-spread": "error",
  "@eslint-react/jsx-no-leaked-dollar": "error",
  "@eslint-react/jsx-no-leaked-semicolon": "error",
  "@eslint-react/jsx-no-namespace": "error",
  "@eslint-react/jsx-no-useless-fragment": "error",
  "@eslint-react/naming-convention-context-name": "error",
  "@eslint-react/naming-convention-id-name": "error",
  "@eslint-react/naming-convention-ref-name": "error",
  "@eslint-react/no-access-state-in-setstate": "error",
  "@eslint-react/no-array-index-key": "error",
  "@eslint-react/no-children-count": "error",
  "@eslint-react/no-children-for-each": "error",
  "@eslint-react/no-children-map": "error",
  "@eslint-react/no-children-only": "error",
  "@eslint-react/no-children-to-array": "error",
  "@eslint-react/no-clone-element": "error",
  "@eslint-react/no-component-will-mount": "error",
  "@eslint-react/no-component-will-receive-props": "error",
  "@eslint-react/no-component-will-update": "error",
  "@eslint-react/no-context-provider": "error",
  "@eslint-react/no-create-ref": "error",
  "@eslint-react/no-forward-ref": "error",
  "@eslint-react/no-nested-component-definitions": "error",
  "@eslint-react/no-nested-lazy-component-declarations": "error",
  "@eslint-react/no-set-state-in-component-did-update": "error",
  "@eslint-react/no-set-state-in-component-will-update": "error",
  "@eslint-react/no-unnecessary-use-prefix": "error",
  "@eslint-react/no-unstable-context-value": "error",
  "@eslint-react/no-unused-class-component-members": "error",
  "@eslint-react/no-unused-state": "error",
  "@eslint-react/no-use-context": "error",
  "@eslint-react/purity": "error",
  "@eslint-react/rsc-function-definition": "error",
  "@eslint-react/rules-of-hooks": "error",
  "@eslint-react/set-state-in-effect": "error",
  "@eslint-react/set-state-in-render": "error",
  "@eslint-react/static-components": "error",
  "@eslint-react/unsupported-syntax": "error",
  "@eslint-react/use-memo": "error",
  "@eslint-react/use-state": "error",
  "@eslint-react/web-api-no-leaked-event-listener": "error",
  "@eslint-react/web-api-no-leaked-fetch": "error",
  "@eslint-react/web-api-no-leaked-intersection-observer": "error",
  "@eslint-react/web-api-no-leaked-interval": "error",
  "@eslint-react/web-api-no-leaked-resize-observer": "error",
  "@eslint-react/web-api-no-leaked-timeout": "error",
  "class-methods-use-this": [
    "error",
    {
      exceptMethods: [
        "render",
        "getInitialState",
        "getDefaultProps",
        "getChildContext",
        "componentWillMount",
        "UNSAFE_componentWillMount",
        "componentDidMount",
        "componentWillReceiveProps",
        "UNSAFE_componentWillReceiveProps",
        "shouldComponentUpdate",
        "componentWillUpdate",
        "UNSAFE_componentWillUpdate",
        "componentDidUpdate",
        "componentWillUnmount",
        "componentDidCatch",
        "getSnapshotBeforeUpdate",
      ],
    },
  ],
  "no-underscore-dangle": [
    "error",
    {
      allowAfterSuper: false,
      allowAfterThis: false,
      enforceInMethodNames: true,
      allow: ["__REDUX_DEVTOOLS_EXTENSION_COMPOSE__"],
    },
  ],
};

export const react: Linter.Config[] = [
  {
    files: REACT_FILES,
    name: "yarapa/react",
    plugins: {
      "@eslint-react": eslintReact,
    },
    rules: reactRules,
  },
];
