name: Validate Pull Request Titles

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: read # Needed to read the pull request title for semantic validation.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate-title:
    name: Validate pull request title
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Validate pull request title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: true
          disallowScopes: |
            .*[A-Z].*
          subjectPattern: ^.{1,50}$
          subjectPatternError: >-
            The subject "{subject}" in pull request title "{title}" must be between
            1 and 50 characters.
